version: '3.9'

services:
  app:
    container_name: go-posts
    build: .
    ports:
      - 8081:8081
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - postsnet
    restart: on-failure

  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 6000:5432
    restart: always
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - postsnet

networks:
  postsnet:
    driver: bridge