DROP TABLE IF EXISTS users_posts;

DROP TABLE IF EXISTS reports;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS posts;

DROP TABLE IF EXISTS admins;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS verification_type;

DROP TYPE IF EXISTS session_type;